config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  # resources :rooms do 
  #   resources :messages
  # end
  
  get 'home/index'
  devise_for :users

  # devise_scope :user do 
  #   get 'users', to: 'devise/sessions#new'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:redirect('/title')

  
  
  get 'help', to: 'pages#help', as: 'help'
  get 'search', to: 'pages#search', as: 'search'
  get 'editprofile', to: 'pages#editprofile', as: 'editprofile'
  get 'users', to: 'users#show', as: 'users'
  patch 'game/:id', to: 'games#check'
  get 'game/:id', to: 'games#show', as: 'game'
  get 'title', to: 'pages#title', as: 'title'
  get 'home', to: 'pages#home', as: 'home'

  get 'posts', to: 'posts#index', as: 'posts'
  post 'posts', to: 'posts#create'
  get 'posts/new', to: 'posts#new', as: 'new_post'
  get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show', as: 'post'
  delete 'posts/:id', to: 'posts#destroy'


  get 'trending/newest', to: 'trending#newest', as: 'trending_newest'
  get 'trending/oldest', to: 'trending#oldest', as: 'trending_oldest'
  get 'trending/today', to: 'trending#today', as: 'trending_today'
  get 'trending/this-week', to: 'trending#week', as: 'trending_this_week'

  
  patch '/users/:id', to: 'users#report_user_update'
  put '/users/:id', to: 'users#report_user_update'
  get '/users/:id/report-user', to: 'users#report_user', as: 'report_user'
  
  
  # Map requests to users/:id to user controller "show"
  # Map requests to users/:id to user
  # Maps requests to users/:id/edit
  resources :users, only: [:show, :edit, :update, :report_user, :report_user_update]
  resource :posts, only: [:new, :create, :show, :destroy]

  # Searching for posts by hashtag
  get 'search' => 'search#index'


end

app/views/shared/_navbar.html.erb
<div style="position: sticky; top: 0; width: 100%; overflow: hidden;">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/title"><%= image_tag 'CustomIcon.jpeg', class: 'd-block mx-auto', style: 'max-width: 2.6rem;' %></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= active_class(posts_path) %>" style="height: 32px">                
          <%= link_to posts_path do %><i class="fa-solid fa-house fa-2xl" style="color:white; margin: 0 1rem"></i> <% end %>
        </li>
        <li class="nav-item <%= active_class(trending_newest_path) %>" style="height: 32px">                
          <%= link_to trending_newest_path do %><i class="fa-solid fa-arrow-trend-up fa-2xl" style="color:white; margin: 0 1rem"></i> <% end %>
        </li>        
        </li>
      </ul>
    </div>

    <div class="mx-auto order-0">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item <%= active_class(search_path) %>" style="height: 32px">                
          <%= link_to search_path do %><i class="fa-solid fa-magnifying-glass fa-2xl" style="color:white; margin-right: 135px"></i> <% end %>
        </li>
      </ul>
    </div>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>

        <!-- User Edit Account Settings-->
          <li class="nav-item <%= active_class(edit_user_registration_path) %>" style="height: 32px">                
            <%= link_to edit_user_registration_path do %><i class="fa-solid fa-gear fa-2xl" style="color:white; margin: 0 1rem"></i> <% end %>
          </li>

          <!-- User Profile Page -->
          <li class="nav-item <%= active_class(users_path) %>" style="height: 32px">                
            <%= link_to users_path do %><i class="fa-solid fa-user fa-2xl" style="color:white; margin: 0 1rem"></i> <% end %>
          </li>

          <!-- User Signout -->
          <li class="nav-item <%= active_class(destroy_user_session_path) %>" style="height: 32px">                
            <%= button_to destroy_user_session_path, method: :delete do %><i class="fa-solid fa-right-from-bracket fa-2xl" style="color:white;  margin: 0 1rem"></i> <% end %>
          </li>
        <% else %>
        <!-- User Login -->
          <li class="nav-item <%= active_class(new_user_session_path) %>" style="height: 32px">                
            <%= link_to new_user_session_path do %><i class="fa-solid fa-right-to-bracket fa-2xl" style="color:white; margin: 0 1rem"></i> <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>