config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  # resources :rooms do 
  #   resources :messages
  # end
  
  get 'home/index'
  devise_for :users

  # devise_scope :user do 
  #   get 'users', to: 'devise/sessions#new'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:redirect('/title')

  
  
  get 'help', to: 'pages#help', as: 'help'
  get 'search', to: 'pages#search', as: 'search'
  get 'editprofile', to: 'pages#editprofile', as: 'editprofile'
  get 'users', to: 'users#show', as: 'users'
  patch 'game/:id', to: 'games#check'
  get 'game/:id', to: 'games#show', as: 'game'
  get 'title', to: 'pages#title', as: 'title'
  get 'home', to: 'pages#home', as: 'home'

  get 'posts', to: 'posts#index', as: 'posts'
  post 'posts', to: 'posts#create'
  get 'posts/new', to: 'posts#new', as: 'new_post'
  get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show', as: 'post'
  delete 'posts/:id', to: 'posts#destroy'


  get 'trending/newest', to: 'trending#newest', as: 'trending_newest'
  get 'trending/oldest', to: 'trending#oldest', as: 'trending_oldest'
  get 'trending/today', to: 'trending#today', as: 'trending_today'
  get 'trending/this-week', to: 'trending#week', as: 'trending_this_week'

  
  patch '/users/:id', to: 'users#report_user_update'
  put '/users/:id', to: 'users#report_user_update'
  get '/users/:id/report-user', to: 'users#report_user', as: 'report_user'
  
  
  # Map requests to users/:id to user controller "show"
  # Map requests to users/:id to user
  # Maps requests to users/:id/edit
  resources :users, only: [:show, :edit, :update, :report_user, :report_user_update]
  resource :posts, only: [:new, :create, :show, :destroy]

  # Searching for posts by hashtag
  get 'search' => 'search#index'


end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  content     :string
#  date        :date
#  description :string
#  isPublic    :boolean
#  likes       :integer
#  postID      :integer
#  title       :string
#  userID      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord

  # Association to user
  belongs_to :user # ----TODO----

  # one-to-one reltionship between Post and Image.
  has_one_attached :post_image
  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  # user-posts association
  belongs_to(
    :creator,
    class_name: 'User',
    foreign_key: 'user_id',
    inverse_of: :posts
  )

  # A new post should 
  validates :title, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]   #<<<< These are commented out until I find out what exactly need's to be excluded
  before_action :require_permission, except: [:index, :show, :new, :create] #<<<< same
  before_action :user_banned, except: [:index, :show] # when a user is banned (i.e. he was reported 5 times) he will only have access to index and show.

  def index
    @posts = Post.order(date: :desc)

    if current_user.reportCount == nil
      current_user.update(reportCount: 0)
    end

    render :index
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  # def create
  #   @post = current_user.posts.build(params.require(:post).permit(:content, :post_image, :isPublic, :title)) #need variables in "permit" here
  #   if @post.save
  #     @post.update(date: Date.current)
  #     flash[:success] = 'User post was successfully created.'
  #     redirect_to post_path(@post)
  #   else
  #     flash.now[:error] = 'Unable to create user post.'
  #     render :new
  #   end
  # end

  #
  # Create post from post_params
  #
  def create
    Post.create(post_params)

    redirect_to root_path
  end

  # 
  private 

  def post_params
    params.require(:post).permit(:descrption, :post_image, :user_id)
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit(:content, :post_image, :isPublic, :title)) 
      flash[:success] = 'User post was successfully updated.'
      redirect_to post_path(@post)
    else
      flash.now[:error] = 'Unable to update user post.'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = 'User post was successfully destroyed.'
    redirect_to posts_url
  end

  
  def require_permission
    if Post.find(params[:id]).creator != current_user
      redirect_to posts_path, flash: { error: "You do not have permission to do that." }
    end
  end

  def user_banned
    if current_user.reportCount == nil
      current_user.update(reportCount: 0)
    end

    if current_user.reportCount >= 5
      redirect_to title_path, flash: { error: "You've been banned!"}
    end
  end

  # validate :image_presence
  def image_presence
    errors.add(:post_image, "can't be blank") unless post_image.attached?
  end

  # after_commit :create_hash_tags, on: :create
def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= bootstrap_form_with model: @post, url: post_path(@post), method: :patch, local: true do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.file_field :post_image %>
  <%= f.select :isPublic, [true, false], label: "Public:" %>
  <%= f.submit %>
<% end %>

<%= link_to "Cancel", posts_path, class: 'btn btn-secondary' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div>
    <h1 style="font-style: italic;"><center><%= post.title %></center></h1>

    <div style="float: left;">
      <% if post.isPublic == true %>
        <i class="fa-solid fa-earth-americas"></i>
      <% else %>
        <i class="fa-solid fa-user-group"></i>
      <% end %>
    </div>

    <div style="float: right;">
      <% if post.creator == current_user %> 
        <td><%= link_to "Edit Post", edit_post_path(post), class: 'btn btn-secondary' %></td>
        <td><%= link_to "Delete Post", post_path(post), method: :delete, class: 'btn btn-danger' %></td>       
      <% end %>
    </div>

    <% if post.creator == current_user %>
      <p style="clear: both; font-size: 15px;">Published by <%= post.creator.userName %></p>
    <% else %>
      <p style="clear: both; font-size: 15px;">Published by <%= post.creator.userName %> <%= link_to 'Report', report_user_path(post.creator), class: 'btn btn-secondary' %></p>
    <% end %>
    
    <% if post.date != nil %>
      <p>Date: <%= post.date.strftime("%m/%d/%Y") %></p>
    <% end %>

    <% if post.post_image.attached? %>
      <div class="my-4">
        <%= image_tag post.post_image, class: 'w-100 d-block mx-auto', style: 'max-width: 32rem; max-height: 20rem; object-fit: contain; border-radius: 9%; border-style: solid; border-color: black; border-width: 3px;' %>
      </div>
    <% end %>
    <p style="clear: both; font-size: 20px;"><%= post.content %></p>
    <hr style="height: 3px; background-color: black; margin-top: 2cm; margin-bottom: 2cm;" />
  </div>
<% end %>
<% if user_signed_in? %>
  <%= link_to "Create Post", new_post_path, class: 'btn btn-primary', style: 'position: -webkit-sticky; position: sticky; bottom: 20px; padding: 10px;' %>
<% end %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= bootstrap_form_with model: @post, url: posts_path, method: :post, local: true do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.file_field :post_image %>
  <%= f.select :isPublic, [true, false], label: "Public:" %>
  <%= f.submit %>

<% end %>

<%= link_to "Cancel", posts_path, class: 'btn btn-secondary' %>

app/views/posts/show.html.erb
<h1 style="font-style: italic;"><center><%= @post.title %></center></h1>

<div style="float: left;">
  <% if @post.isPublic == true %>
    <i class="fa-solid fa-earth-americas"></i>
  <% else %>
    <i class="fa-solid fa-user-group"></i>
  <% end %>
</div>

<div style="float: right;">
  <% if @post.creator == current_user %> 
    <td><%= link_to "Edit Post", edit_post_path(@post), class: 'btn btn-secondary' %></td>
    <td><%= link_to "Delete Post", post_path(@post), method: :delete, class: 'btn btn-danger' %></td>       
  <% end %>
</div>

<p style="clear: both; font-size: 15px;">Published by <%= @post.creator.userName %></p>

<% if @post.date != nil %>
  <p>Date: <%= @post.date.strftime("%m/%d/%Y") %></p>
<% else %>
  <p>Date: none</p>
<% end %>

<p style="clear: both; font-size: 20px;"><%= @post.content %></p>
<% if @post.post_image.attached? %>
  <div class="my-4">
    <%= image_tag @post.post_image, class: 'w-100 d-block mx-auto', style: 'max-width: 32rem; max-height: 20rem; object-fit: contain; border-radius: 9%; border-style: solid; border-color: black; border-width: 3px;' %>
  </div>
<% end %>

<%= link_to "Back to Posts", posts_path, class: 'btn btn-secondary' %>

<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <%= @post.description %>
    </div>
  </div>
</div>

<div class="delete">
  <% if current_user.posts.exists?(@post.id) %>
    <%= link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>