config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  # resources :rooms do 
  #   resources :messages
  # end
  
  get 'home/index'
  devise_for :users

  # devise_scope :user do 
  #   get 'users', to: 'devise/sessions#new'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to:redirect('/title')

  
  
  get 'help', to: 'pages#help', as: 'help'
  get 'search', to: 'pages#search', as: 'search'
  get 'editprofile', to: 'pages#editprofile', as: 'editprofile'
  get 'users', to: 'users#show', as: 'users'
  patch 'game/:id', to: 'games#check'
  get 'game/:id', to: 'games#show', as: 'game'
  get 'title', to: 'pages#title', as: 'title'
  get 'home', to: 'pages#home', as: 'home'

  get 'posts', to: 'posts#index', as: 'posts'
  post 'posts', to: 'posts#create'
  get 'posts/new', to: 'posts#new', as: 'new_post'
  get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show', as: 'post'
  delete 'posts/:id', to: 'posts#destroy'


  get 'trending/newest', to: 'trending#newest', as: 'trending_newest'
  get 'trending/oldest', to: 'trending#oldest', as: 'trending_oldest'
  get 'trending/today', to: 'trending#today', as: 'trending_today'
  get 'trending/this-week', to: 'trending#week', as: 'trending_this_week'

  
  patch '/users/:id', to: 'users#report_user_update'
  put '/users/:id', to: 'users#report_user_update'
  get '/users/:id/report-user', to: 'users#report_user', as: 'report_user'
  
  
  # Map requests to users/:id to user controller "show"
  # Map requests to users/:id to user
  # Maps requests to users/:id/edit
  resources :users, only: [:show, :edit, :update, :report_user, :report_user_update]
  resource :posts, only: [:new, :create, :show, :destroy]

  # Searching for posts by hashtag
  get 'search' => 'search#index'


end

app/controllers/trending_controller.rb
class TrendingController < ApplicationController

  def newest
    @posts = Post.order(date: :desc)
    render :newest
  end

  def oldest
    @posts = Post.order(date: :asc)
    render :oldest
  end

  def today
    @posts = Post.where(date: (Date.today))
    render :today
  end
  
  def week
    @posts = Post.where(date: (Date.today - 7.days)..Date.today)
    render :week
  end

end

app/helpers/trending_helper.rb
module TrendingHelper
end

app/views/trending/newest.html.erb
<div style="float: right;">
  <%= link_to 'Oldest', trending_oldest_path, class: 'btn btn-secondary' %>
  <%= link_to 'Today', trending_today_path, class: 'btn btn-secondary' %>
  <%= link_to 'This Week', trending_this_week_path, class: 'btn btn-secondary' %>
</div>

<h1 style="clear: both; margin-bottom: 2cm; font-family: Copperplate;"><center>Trending</center></h1>

<% @posts.each do |post| %>
  <% if post.isPublic == true %>
    <div>
      <h2 style="font-style: italic;"><center><%= post.title %></center></h2>

      <div style="float: left;">
        <% if post.isPublic == true %>
          <i class="fa-solid fa-earth-americas"></i>
        <% else %>
          <i class="fa-solid fa-user-group"></i>
        <% end %>
      </div>

      <p style="clear: both; font-size: 15px;">Published by <%= post.creator.userName %></p>
      <% if post.date != nil %>
        <p>Date: <%= post.date.strftime("%m/%d/%Y") %></p>
      <% end %>

      <% if post.post_image.attached? %>
        <div class="my-4">
          <%= image_tag post.post_image, class: 'w-100 d-block mx-auto', style: 'max-width: 32rem; max-height: 20rem; object-fit: contain; border-radius: 9%; border-style: solid; border-color: black; border-width: 3px;' %>
        </div>
      <% end %>
      <p style="clear: both; font-size: 20px;"><%= post.content %></p>
      <hr style="height: 3px; background-color: black; margin-top: 2cm; margin-bottom: 2cm;" />
    </div>
  <% end %>
<% end %>

app/views/trending/oldest.html.erb
<div style="float: right;">
  <%= link_to 'Newest', trending_newest_path, class: 'btn btn-secondary' %>
  <%= link_to 'Today', trending_today_path, class: 'btn btn-secondary' %>
  <%= link_to 'This Week', trending_this_week_path, class: 'btn btn-secondary' %>
</div>

<h1 style="clear: both; margin-bottom: 2cm; font-family: Copperplate;"><center>Trending</center></h1>

<% @posts.each do |post| %>
  <% if post.isPublic == true %>
    <div>
      <h2 style="font-style: italic;"><center><%= post.title %></center></h2>

      <div style="float: left;">
        <% if post.isPublic == true %>
          <i class="fa-solid fa-earth-americas"></i>
        <% else %>
          <i class="fa-solid fa-user-group"></i>
        <% end %>
      </div>

      <p style="clear: both; font-size: 15px;">Published by <%= post.creator.userName %></p>
      <% if post.date != nil %>
        <p>Date: <%= post.date.strftime("%m/%d/%Y") %></p>
      <% end %>

      <% if post.post_image.attached? %>
        <div class="my-4">
          <%= image_tag post.post_image, class: 'w-100 d-block mx-auto', style: 'max-width: 32rem; max-height: 20rem; object-fit: contain; border-radius: 9%; border-style: solid; border-color: black; border-width: 3px;' %>
        </div>
      <% end %>
      <p style="clear: both; font-size: 20px;"><%= post.content %></p>
      <hr style="height: 3px; background-color: black; margin-top: 2cm; margin-bottom: 2cm;" />
    </div>
  <% end %>
<% end %>

app/views/trending/today.html.erb
<div style="float: right;">
  <%= link_to 'Newest', trending_newest_path, class: 'btn btn-secondary' %>
  <%= link_to 'Oldest', trending_oldest_path, class: 'btn btn-secondary' %>
  <%= link_to 'This Week', trending_this_week_path, class: 'btn btn-secondary' %>
</div>

<h1 style="clear: both; margin-bottom: 2cm; font-family: Copperplate;"><center>Trending</center></h1>

<% @posts.each do |post| %>
  <% if post.isPublic == true %>
    <div>
      <h2 style="font-style: italic;"><center><%= post.title %></center></h2>

      <div style="float: left;">
        <% if post.isPublic == true %>
          <i class="fa-solid fa-earth-americas"></i>
        <% else %>
          <i class="fa-solid fa-user-group"></i>
        <% end %>
      </div>

      <p style="clear: both; font-size: 15px;">Published by <%= post.creator.userName %></p>
      <% if post.date != nil %>
        <p>Date: <%= post.date.strftime("%m/%d/%Y") %></p>
      <% end %>

      <% if post.post_image.attached? %>
        <div class="my-4">
          <%= image_tag post.post_image, class: 'w-100 d-block mx-auto', style: 'max-width: 32rem; max-height: 20rem; object-fit: contain; border-radius: 9%; border-style: solid; border-color: black; border-width: 3px;' %>
        </div>
      <% end %>
      <p style="clear: both; font-size: 20px;"><%= post.content %></p>
      <hr style="height: 3px; background-color: black; margin-top: 2cm; margin-bottom: 2cm;" />
    </div>
  <% end %>
<% end %>

app/views/trending/week.html.erb
<div style="float: right;">
  <%= link_to 'Newest', trending_newest_path, class: 'btn btn-secondary' %>
  <%= link_to 'Oldest', trending_oldest_path, class: 'btn btn-secondary' %>
  <%= link_to 'Today', trending_today_path, class: 'btn btn-secondary' %>
</div>

<h1 style="clear: both; margin-bottom: 2cm; font-family: Copperplate;"><center>Trending</center></h1>

<% @posts.each do |post| %>
  <% if post.isPublic == true %>
    <div>
      <h2 style="font-style: italic;"><center><%= post.title %></center></h2>

      <div style="float: left;">
        <% if post.isPublic == true %>
          <i class="fa-solid fa-earth-americas"></i>
        <% else %>
          <i class="fa-solid fa-user-group"></i>
        <% end %>
      </div>

      <p style="clear: both; font-size: 15px;">Published by <%= post.creator.userName %></p>
      <% if post.date != nil %>
        <p>Date: <%= post.date.strftime("%m/%d/%Y") %></p>
      <% end %>

      <% if post.post_image.attached? %>
        <div class="my-4">
          <%= image_tag post.post_image, class: 'w-100 d-block mx-auto', style: 'max-width: 32rem; max-height: 20rem; object-fit: contain; border-radius: 9%; border-style: solid; border-color: black; border-width: 3px;' %>
        </div>
      <% end %>
      <p style="clear: both; font-size: 20px;"><%= post.content %></p>
      <hr style="height: 3px; background-color: black; margin-top: 2cm; margin-bottom: 2cm;" />
    </div>
  <% end %>
<% end %>